### ISSUE TITLE
Price Page Issues

### ISSUE THREAD

**Issue by dkkaran1996** [vac-soft/vac-soft.github.io#7]
1. The Price page URL is marked as http. It should not be like that.
2. Title of page is not visible due to background
3. The Sales CRM background color is not matched

**Comment by abdulfahadlee** [comment]
> 1. The Price page URL is marked as http. It should not be like that.
> 2. Title of page is not visible due to background
> 3. The Sales CRM background color is not matched

Fixed the bug and added new colors for a page

**Comment by dkkaran1996** [comment]
@abdulfahadlee  Some other issues in that commit. Please resolve those issues and commit. Let me check and then close
